version: "3"
services:
  postgresql:
    image: "postgres"
    container_name: "postgres-db"
    environment:
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=student
      - POSTGRES_DB=studentdb
#   Maps port 5555 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5555:5432"
#   Set a volume some that database is not lost after shutting down the container.
    volumes:
      - ./postgres-data:/var/lib/postgresql/data